# -*- coding: utf-8 -*-
"""Proyecto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZuR34AXm8fVdTLo8lKUpxx0vHFo8VEd

# Proyecto 1: Implementación de FFT Radix-2 (Cooley-Tukey) desde cero

Este *notebook* presenta el desarrollo algorítmico de la Transformada Rápida de Fourier (FFT) para $N=512$ puntos, utilizando la variante Radix-2 con decimación en tiempo (DIT).

Para fines didácticos sobre la estructura del procesamiento digital de señales, **no se utilizan comandos directos de FFT** (como `scipy.fft` o `numpy.fft.fft`). En su lugar, el algoritmo se construye paso a paso estructurando la operación básica de "mariposa" y orquestando el cruce de datos etapa por etapa.

## 1. Definición del Algoritmo y Funciones Base

El algoritmo requiere tres componentes fundamentales, los cuales están programados en la siguiente celda:

1. **`ordenamiento_inversion_bits(x)`**: Algoritmo de *bit-reversal* que reordena las muestras de entrada. Este es el primer paso obligatorio en un esquema de decimación en tiempo para que los datos fluyan correctamente por la red.
2. **`mariposa_2x2(a, b, factor_giro)`**: La operación matemática más pequeña de la FFT. Toma dos números complejos y un factor de giro ($W_N^k$) para producir dos salidas.
3. **`fft_cooley_tukey(x)`**: Función principal que itera a través de las $\log_2(N)$ etapas, agrupando las muestras y calculando progresivamente el espectro utilizando la mariposa.
"""

import numpy as np
import matplotlib.pyplot as plt

def ordenamiento_inversion_bits(x):
    N = len(x)
    num_bits = int(np.log2(N))
    x_reordenado = np.zeros(N, dtype=complex)
    for i in range(N):
        bit_string = '{:0{width}b}'.format(i, width=num_bits)
        indice_invertido = int(bit_string[::-1], 2)
        x_reordenado[indice_invertido] = x[i]
    return x_reordenado

def mariposa_2x2(a, b, factor_giro):
    salida_1 = a + factor_giro * b
    salida_2 = a - factor_giro * b
    return salida_1, salida_2

def fft_cooley_tukey(x):
    N = len(x)

    if N & (N - 1) != 0:
        raise ValueError("El tamaño de la señal N debe ser una potencia de 2")

    X = ordenamiento_inversion_bits(x)

    etapas = int(np.log2(N))

    for etapa in range(1, etapas + 1):
        tamano_bloque = 2 ** etapa
        mitad_bloque = tamano_bloque // 2

        W_N = np.exp(-1j * 2 * np.pi / tamano_bloque)

        for k in range(0, N, tamano_bloque):
            W = 1 + 0j

            for j in range(mitad_bloque):
                indice_superior = k + j
                indice_inferior = k + j + mitad_bloque

                X[indice_superior], X[indice_inferior] = mariposa_2x2(
                    X[indice_superior],
                    X[indice_inferior],
                    W
                )

                W = W * W_N
    return X

"""## 2. Generación de Señal de Prueba y Enventanado

Para validar la FFT, creamos un escenario de prueba con los siguientes parámetros:
* **Señal original**: Una suma de dos ondas senoidales puras (50 Hz y 120 Hz) muestreadas a 1000 Hz.
* **Tamaño de la FFT ($N$)**: 512 puntos.
* **Ventana**: Rectangular de 256 puntos.

Al multiplicar la señal de 512 puntos por una ventana rectangular que solo vale $1$ en sus primeros 256 índices y $0$ en el resto, estamos aplicando un truncamiento seguido de un *zero-padding* (relleno de ceros) implícito. Esto permite mantener el tamaño de $N=512$ exigido por el algoritmo radix-2 e interpola artificialmente el espectro para una mejor visualización.
"""

N = 512
fs = 1000
t = np.arange(N) / fs

f1 = 50.0
f2 = 120.0
senal_original = np.sin(2 * np.pi * f1 * t) + 0.5 * np.sin(2 * np.pi * f2 * t)

ventana_rectangular = np.zeros(N)
ventana_rectangular[:256] = 1

senal_enventanada = senal_original * ventana_rectangular

X_fft = fft_cooley_tukey(senal_enventanada)

magnitud = np.abs(X_fft)[:N//2]
frecuencias = (fs / N) * np.arange(N//2)

"""## 3. Visualización en el Dominio del Tiempo y la Frecuencia

En esta última etapa, extraemos la magnitud absoluta del arreglo complejo devuelto por nuestra función `fft_cooley_tukey` y graficamos los resultados. Por el teorema de Nyquist, solo graficamos la primera mitad del espectro (frecuencias positivas hasta $f_s/2$).
"""

plt.figure(figsize=(12, 8))

plt.subplot(2, 1, 1)
plt.plot(t, senal_original, label='Señal Original', alpha=0.5, linestyle='--')
plt.plot(t, senal_enventanada, label='Señal con Ventana Rectangular (256 pts)', color='red')
plt.title('Señal de Prueba en el Dominio del Tiempo')
plt.xlabel('Tiempo [s]')
plt.ylabel('Amplitud')
plt.legend()
plt.grid(True)

plt.subplot(2, 1, 2)
plt.stem(frecuencias, magnitud, basefmt="b-")
plt.title(f'Espectro de Magnitud FFT Cooley-Tukey (N={N})')
plt.xlabel('Frecuencia [Hz]')
plt.ylabel('Magnitud |X(f)|')
plt.xlim(0, 200)
plt.grid(True)

plt.tight_layout()
plt.show()

"""## 4. Reconstrucción de la Señal (IFFT)

Para regresar del dominio de la frecuencia al dominio del tiempo, necesitamos aplicar la Transformada Rápida de Fourier Inversa (IFFT). Matemáticamente, la ecuación de la IDFT es casi idéntica a la DFT, con solo dos diferencias fundamentales:

1. **Signo del exponente:** El factor de giro $W_N$ ahora tiene un exponente positivo ($e^{+j\frac{2\pi}{N}}$) en lugar de negativo.
2. **Factor de escalamiento:** El resultado final de toda la sumatoria debe dividirse entre el número total de muestras $N$.

Gracias a la modularidad de nuestro algoritmo Radix-2, podemos copiar la estructura exacta de la función `fft_cooley_tukey`, cambiar el signo en el cálculo de `W_N` y agregar la división final por $N$ para reconstruir la señal original.
"""

def ifft_cooley_tukey(X):
    N = len(X)
    if N & (N - 1) != 0:
        raise ValueError("El tamaño de la señal N debe ser una potencia de 2")

    x_rec = ordenamiento_inversion_bits(X.copy())

    etapas = int(np.log2(N))

    for etapa in range(1, etapas + 1):
        tamano_bloque = 2 ** etapa
        mitad_bloque = tamano_bloque // 2

        W_N = np.exp(1j * 2 * np.pi / tamano_bloque)

        for k in range(0, N, tamano_bloque):
            W = 1 + 0j
            for j in range(mitad_bloque):
                indice_superior = k + j
                indice_inferior = k + j + mitad_bloque

                x_rec[indice_superior], x_rec[indice_inferior] = mariposa_2x2(
                    x_rec[indice_superior],
                    x_rec[indice_inferior],
                    W
                )

                W = W * W_N

    return x_rec / N

senal_reconstruida = ifft_cooley_tukey(X_fft)

senal_reconstruida_real = np.real(senal_reconstruida)

plt.figure(figsize=(12, 6))

plt.plot(t, senal_enventanada, label='Señal Original Enventanada (Entrada de la FFT)', linewidth=4, alpha=0.4, color='blue')
plt.plot(t, senal_reconstruida_real, label='Señal Reconstruida (Salida de la IFFT)', linestyle='--', color='red')

plt.title('Comprobación del Algoritmo: Reconstrucción de la Señal (IFFT)')
plt.xlabel('Tiempo [s]')
plt.ylabel('Amplitud')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

mse = np.mean((senal_enventanada - senal_reconstruida_real)**2)
print(f"Error Cuadrático Medio (MSE) de la reconstrucción: {mse:.2e}")

"""## 5. Análisis de la Reconstrucción

Al graficar la salida de la IFFT sobre la señal temporal enventanada original, observamos un traslape perfecto.

Adicionalmente, el cálculo del **Error Cuadrático Medio (MSE)** entre ambos vectores arroja un valor cercano a cero (en el orden de $10^{-30}$ o similar). Este error no es cero absoluto únicamente debido a las limitaciones de precisión de punto flotante de la computadora al manejar números irracionales en la función exponencial de los factores de giro. Esto demuestra que nuestra arquitectura Radix-2 bidireccional funciona correctamente sin pérdida de información.
"""